database:
  image: postgres:9.1
  volumes:
    - /ShallWeDebate/postgres-entrypoint:/docker-entrypoint-initdb.d:ro
  env_file:
    - ./vars.env
web:
  image: ingensi/play-framework:2.3.8
  volumes:
    - /ShallWeDebate:/app:rw
  env_file:
    - ./vars.env
  links:
    - database
  ports:
    - "80:9000"
  stdin_open: true
